name: Deploy Demo Site

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - name: Build docs
        run: |
          DOCS_BASE=/rovemaps-camera-controls/ npm run docs:build
      - name: Build demo site
        working-directory: examples/site
        run: |
          npm ci
          VITE_BASE=/rovemaps-camera-controls/demo/ npm run build
      - name: Assemble publish directory
        run: |
          rm -rf public
          mkdir -p public/demo
          cp -r docs/.vitepress/dist/* public/
          cp -r examples/site/dist/* public/demo/
          touch public/.nojekyll
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          force_orphan: true
