name: Deploy Docs + Demo via Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm install
      - name: Build library
        run: npm run build
      - name: Build docs
        run: |
          DOCS_BASE=/rovemaps-camera-controls/ npm run docs:build
      - name: Build demo
        working-directory: examples/site
        run: |
          npm install
          rm -rf node_modules/.vite
          VITE_BASE=/rovemaps-camera-controls/demo/ npm run build
      - name: Assemble static site
        run: |
          rm -rf public && mkdir -p public/demo
          cp -r docs/.vitepress/dist/* public/
          cp -r examples/site/dist/* public/demo/
          touch public/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

